# Document Similarity: TF-IDF

In [5]:
import numpy as np
import re
import os

In [37]:
## Remove the numbers at the start and end of the documents.
DATAFILE = "./Data/LeePincombeWelshDocuments.txt"
CLEANFILE = "./Data/cleanLPW.txt"
INDIVIDUAL_DOCS = "./Data/Docs"

if (os.path.exists(CLEANFILE)):
    os.remove(CLEANFILE)
i = 0
with open(DATAFILE, 'r', encoding="utf8", errors="ignore") as inputfile:
     lines = inputfile.readlines()
     for line in lines:
        start_removed = re.sub("(\d*\.\s)", "", line)
        end_removed = re.sub("\(\d* words\)", ".", start_removed)
        with open(CLEANFILE, 'a+') as outputfile:
            outputfile.write(end_removed)
        with open(INDIVIDUAL_DOCS+f"/{i}.txt", "w+") as docfile:
            docfile.write(end_removed)
            i = i + 1

     

In [24]:
!pip3 install stanza
import stanza
print("Downloading English model...")
stanza.download('en')



def tokenize_and_normalize(file_name, stopwords):
    """Tokenizes, lemmatizes, lowercases and removes stop words.
    
    this function takes in a path to a song, reads the song file,
    tokenizes it into words, then lemmatizes and lowercases these words.
    finally, stopwords given to the function are removed from the list of song lemmas
    
    Parameters
    ----------
    file_name : str
        a path to a text file
    stopwords : list of strings
        stopwords that should be removed
    
    Returns
    -------
    normalized_song : list of strings
        a song represented as a list of its lemmas
    """
    
    nlp = stanza.Pipeline(lang='en', processors='tokenize, lemma',  verbose=False)
    
    with open(file_name, 'r') as f:
        line = f.read()
        doc = nlp(line)
    normalized_doc = []
    for doc_sent in doc.sentences:
        for words in doc_sent.words:
            if words.lemma.lower() not in stopwords:
                lemma = words.lemma.lower()
                normalized_doc.append(lemma)
    
    return normalized_doc

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621


2022-04-18 18:26:36 INFO: Downloading default packages for language: en (English)...
2022-04-18 18:26:37 INFO: File exists: /Users/esapalosaari/stanza_resources/en/default.zip.
2022-04-18 18:26:40 INFO: Finished downloading models and saved to /Users/esapalosaari/stanza_resources.


In [25]:
def tf_idf(td_matrix):
    """ Weighs a term-document matrix of raw counts with tf-idf scheme
    
    this function takes in a term-document matrix as a numpy array, 
    and weights the scores with the tf-idf algorithm described above.
    idf values are modified with log_10
    
    Parameters
    ----------
    td_matrix : numpy array 
        a matrix where columns are songs and 
        rows are word counts in a song
    
    Returns
    -------
    tf_idf_matrix : numpy array 
        a matrix where columns are songs and 
        rows are word tf-idf values in a song
        
    idf_vector : numpy array of shape (vocabulary-size, 1)
        a vector of idf values for words in the collection. the shape is (vocabulary-size, 1)
        this vector will be used to weight new query documents
    """
    # YOUR CODE HERE
    idf_vector = []
    for row in td_matrix:
        nonzeros = np.count_nonzero(row)
        documents = len(row)
        if nonzeros > 0:
            idf = np.log10(documents/nonzeros)
        else:
            idf = 0
        idf_vector.append(idf)
    
    idf_vector = np.array(idf_vector)
    idf_vector = idf_vector.reshape((len(idf_vector), 1))
    tf_idf_matrix = idf_vector * td_matrix
    
    return tf_idf_matrix, idf_vector  

## Prepare documents

In [26]:
!pip3 install nltk

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 2.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.9/288.9 KB 1.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.0/307.0 KB 2.2 MB/s eta 0:00:00a 0:00:01
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at ht

In [27]:

import glob
import nltk
import ssl
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download("stopwords")
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/esapalosaari/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [38]:
stopwords_english = stopwords.words('english')
docs = glob.glob('./Data/Docs/*')


['./Data/Docs/29.txt', './Data/Docs/15.txt', './Data/Docs/14.txt', './Data/Docs/28.txt', './Data/Docs/16.txt', './Data/Docs/17.txt', './Data/Docs/13.txt', './Data/Docs/12.txt', './Data/Docs/10.txt', './Data/Docs/38.txt', './Data/Docs/39.txt', './Data/Docs/11.txt', './Data/Docs/49.txt', './Data/Docs/48.txt', './Data/Docs/9.txt', './Data/Docs/8.txt', './Data/Docs/5.txt', './Data/Docs/43.txt', './Data/Docs/42.txt', './Data/Docs/4.txt', './Data/Docs/40.txt', './Data/Docs/6.txt', './Data/Docs/7.txt', './Data/Docs/41.txt', './Data/Docs/45.txt', './Data/Docs/51.txt', './Data/Docs/3.txt', './Data/Docs/50.txt', './Data/Docs/2.txt', './Data/Docs/44.txt', './Data/Docs/0.txt', './Data/Docs/46.txt', './Data/Docs/47.txt', './Data/Docs/1.txt', './Data/Docs/34.txt', './Data/Docs/20.txt', './Data/Docs/21.txt', './Data/Docs/35.txt', './Data/Docs/23.txt', './Data/Docs/37.txt', './Data/Docs/36.txt', './Data/Docs/22.txt', './Data/Docs/26.txt', './Data/Docs/32.txt', './Data/Docs/33.txt', './Data/Docs/27.txt

In [34]:
normalized_docs = []

for i, doc_path in enumerate(docs):
    normalized_docs.append(tokenize_and_normalize(doc_path, stopwords_english))
print(normalized_docs)

[['labor', 'need', 'distinguish', 'government', 'issue', 'asylum', 'seeker', ',', 'greens', 'leader', 'bob', 'brown', 'saidhis', 'senate', 'colleague', 'kerry', 'nettle', 'intend', 'move', 'motion', 'today', '-', 'first', 'anniversary', 'tampa', 'crisis', '-', 'condemn', 'government', 'refugee', 'policy', 'call', 'end', 'mandatory', 'detention', '"', 'greens', 'want', 'bring', 'government', 'book', 'serial', 'breach', 'international', 'obligation', 'far', 'asylum', 'seeker', 'country', 'concerned', ',', '"', 'senator', 'brown', 'say', 'today', '.'], ['federal', 'government', 'regret', 'action', '12', 'month', 'tampa', 'asylum', 'seeker', 'crisis', ',', 'small', 'business', 'minister', 'joe', 'hockey', 'say', 'today', 'mr', 'hockey', 'say', 'government', 'embarrassed', 'tampa', 'issue', ',', 'begin', 'august', '27', 'last', 'year', 'captain', 'norwegian', 'cargo', 'ship', 'rescue', '400', 'asylum', 'seeker', 'indonesian', 'ferry', 'north', 'christmas', 'island', '.'], ['prince', 'willia

In [39]:
import numpy as np

def create_term_doc_matrix(docs_normalized):
    """ Constructs a frequency term-document matrix
    
    this function takes in a list of songs and returns a term-document matrix
    the rows are lemma types, the columns are songs 
    the rows should be sorted alphabetically
    the order of the columns should be preserved as it's given in docs_normalized
    the cell values are a number of times a lemma was seen in a song
    the value should be zero, if a lemma is absent from a song
    
    Parameters
    ----------
    docs_normalized : a list of lists of strings [['a','a','b'], ['a','b','c']]
        a list of songs represented as a list of lemmas
    
    Returns
    -------
    matrix : numpy array
        a matrix where columns are songs and rows are lemma types,
        the cells of the matrix contain lemma counts in a song,
        the lemmas for rows are sorted alphabetically
        for the example above it will be:
            np.array([[2,1],
                      [1,1],
                      [0,1]])
        
    sorted_vocab : list of strings
        a list of all the lemma types used in all songs (the rows of our matrix)
        the words should be strings sorted alphabetically
        for the example above it should be ['a','b','c']
    """
    
    # 1. create one ordered list of all terms
    sorted_vocab = []
    for song in docs_normalized:
        sorted_vocab += song
    if sorted_vocab != None:
        sorted_vocab = list(set(sorted_vocab))
        sorted_vocab.sort() 
    
    # 2. count the number of occurences of each term in each song
    # 2.2. add to list of list
    matrix = []
    for term in sorted_vocab:
        term_counts = []
        for song in docs_normalized:
            occurences = song.count(term)
            term_counts.append(occurences)
        matrix.append(term_counts)
    
    matrix = np.array(matrix)
    
    return matrix, sorted_vocab

In [42]:
term_doc_matrix, sorted_vocab = create_term_doc_matrix(normalized_docs)

In [43]:
print(term_doc_matrix)

[[2 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [44]:
def tf_idf(td_matrix):
    """ Weighs a term-document matrix of raw counts with tf-idf scheme
    
    this function takes in a term-document matrix as a numpy array, 
    and weights the scores with the tf-idf algorithm described above.
    idf values are modified with log_10
    
    Parameters
    ----------
    td_matrix : numpy array 
        a matrix where columns are songs and 
        rows are word counts in a song
    
    Returns
    -------
    tf_idf_matrix : numpy array 
        a matrix where columns are songs and 
        rows are word tf-idf values in a song
        
    idf_vector : numpy array of shape (vocabulary-size, 1)
        a vector of idf values for words in the collection. the shape is (vocabulary-size, 1)
        this vector will be used to weight new query documents
    """
    idf_vector = []
    for row in td_matrix:
        nonzeros = np.count_nonzero(row)
        documents = len(row)
        if nonzeros > 0:
            idf = np.log10(documents/nonzeros)
        else:
            idf = 0
        idf_vector.append(idf)
    
    idf_vector = np.array(idf_vector)
    idf_vector = idf_vector.reshape((len(idf_vector), 1))
    tf_idf_matrix = idf_vector * td_matrix
    
    return tf_idf_matrix, idf_vector   

In [45]:
tf_idf_matrix, idf_vector = tf_idf(term_doc_matrix)

In [46]:
def cosine(doc1,doc2):
    """ Computes cosine similarity between two vectors
        
    this function takes in two document vectors and computes cosine similarity between them
    when any of the vectors contains only zeros, their similarity is unknown (no common words)
    your function should output -inf
    
    Parameters
    ----------
    doc1 : numpy array
        the first document vector 
    doc2 : numpy array  
        the second document vector 
    
    Returns
    -------
    score : float 
        cosine similarity
    """
    infinity = float('-inf')

    if np.all(doc1==0) or np.all(doc2==0):
        return infinity
    above = np.dot(doc2, doc1)
    root1 = np.sqrt(np.sum([x**2 for x in doc1]))
    root2 = np.sqrt(np.sum([x**2 for x in doc2]))
    score = above /( root1 * root2)
    return score

In [48]:
print(tf_idf_matrix)

[[0.74716133 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
